[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "psutil>=7.1.0",
    "python-nmap>=0.7.1",
    "sqlalchemy>=2.0.44",
]
